categories:
- Materials science
description: Convert to NeXus
homepage_url: https://github.com/MaterialsGalaxy/larch-tools
long_description: |
  Convert data to NeXus/XDI format.
name: nexuscreator
owner: muon-spectroscopy-computational-project
remote_repository_url: https://github.com/MaterialsGalaxy/larch-tools/tree/main/nexuscreator
