 Feff 6L.02
 Formula:    Cu
 SpaceGroup: Fm-3m
 # sites:    1
 Calculating potentials and phases...
     free atom potential and density for atom type    0
     free atom potential and density for atom type    1
     overlapped potential and density for unique potential    0
     overlapped potential and density for unique potential    1
     muffin tin radii and interstitial parameters
     phase shifts for unique potential    0
     phase shifts for unique potential    1
 Preparing plane wave scattering amplitudes...
   nncrit in prcrit       9
 Searching for paths...
    WARNING in PATHS Module:
       rmax > distance to most distant atom.
       Some paths may be missing.
   rmax, ratx      5.00000     4.42740
     Rmax  5.0000  keep and heap limits   0.0000000   0.0000000
    Preparing neighbor table
     nfound  nheap  nheapx  nsc    r
     Paths found      306   (nheapx, nbx      49   3)
 Eliminating path degeneracies...
     Plane wave chi amplitude filter   2.50%
     Unique paths      7,  total paths     282
 Calculating EXAFS parameters...
     Curved wave chi amplitude ratio   4.00%
     Discard feff.dat for paths with cw ratio <   2.67%
     path  cw ratio     deg    nleg  reff
       1   100.000    12.000     2   2.5562
       2    22.972     6.000     2   3.6150
       3    10.554    48.000     3   3.8342
       4     8.445    48.000     3   4.3636
       5    55.345    24.000     2   4.4274
       6    10.643    48.000     3   4.7699
       7    21.223    96.000     3   4.7699
     7 paths kept,    7 examined.
 Feff done.  Have a nice day.
